version: "3"
services:
  backend:
    image: afoone/ivace_poc
    build: .
    ports:
      - 8080:8080
    command: npx json-server --watch db.json -H 0.0.0.0 --port 8080
  web:
    image: afoone/ivace_poc
    environment: 
      REACT_APP_BASEURL: http://localhost:8080
    depends_on:
      - backend
    ports:
      - 5000:5000

